# Site settings
title: Hao Zhuang
description: 'PhD, UC San Diego, Computer Science, 2016'
url: 'http://zhuangh.github.io' 
baseurl: /
google_analytics: 'UA-73314404-1'

author:
  name: 'Hao Zhuang'
  email: hao.zhuang@cs.ucsd.edu
  twitter_username: zhuangh
  github_username: zhuangh
  linkedin_username: zhuangh

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false


gems: ['jekyll-paginate', 'jekyll-mentions', 'jemoji', 'jekyll-redirect-from', 'jekyll-sitemap', 'jekyll-feed']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
